### ISSUE TITLE
Otto example - IndexError: too many indices for array

### ISSUE THREAD

**Issue by RonLuhtanen** [mpearmain/BayesBoost#1]
Greetings,

Would you happen to know what causes this error while trying to run the Otto example? It manages to initialize the problem but produces the error as it transitions to maximize the function. I'm running the anaconda distribution with python 3.6.

`Initialization
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |   colsample_bytree |     gamma |   learning_rate |   max_delta_step |   max_depth |   min_child_weight |   n_estimators |   subsample | 

    1 | 06m06s |   -0.32531 |             0.6182 |    0.9051 |          0.2812 |           0.0129 |      8.4669 |             2.6626 |       944.8025 |      0.7061 | 

    2 | 02m56s |   -0.27711 |             0.7733 |    0.6258 |          0.1907 |           0.0931 |      5.4166 |             6.0346 |       616.8563 |      0.7488 | 

    3 | 06m30s |   -0.28382 |             0.8422 |    0.0806 |          0.2088 |           0.0239 |      9.3391 |             5.7449 |       749.8462 |      0.7838 | 

    4 | 06m32s |   -0.27949 |             0.9063 |    0.1119 |          0.2483 |           0.0400 |      8.9312 |             4.4974 |       801.3183 |      0.7566 | 

    5 | 00m37s |   -0.44748 |             0.9505 |    0.6875 |          0.1109 |           0.0882 |      5.9782 |             5.9778 |       117.2441 |      0.7775 | 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-14-071b4610577d> in <module>()
     71                                      })
     72 
---> 73     xgboostBO.maximize()
     74     print('-'*53)
     75 

/home/ron/software/anaconda3/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, xi, **gp_params)
    262                         gp=self.gp,
    263                         y_max=y_max,
--> 264                         bounds=self.bounds)
    265 
    266         # Print new header

/home/ron/software/anaconda3/lib/python3.6/site-packages/bayes_opt/helpers.py in acq_max(ac, gp, y_max, bounds)
     53 
     54         # Store it if better than previous minimum(maximum).
---> 55         if max_acq is None or -res.fun[0] >= max_acq:
     56             x_max = res.x
     57             max_acq = -res.fun[0]

IndexError: too many indices for array`

**Comment by GaryGaryry** [comment]
I got the same problem. I just changed **'gamma': (1., 0.01)** to **'gamma': (0.01, 1)**, and problem solved. Hope it work for you! Good luck！
